# Generated by Django 4.2.2 on 2023-08-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Жанр"
                    ),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанри",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Назва")),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="books/posters/",
                        verbose_name="Постер",
                    ),
                ),
                ("description", models.TextField(null=True, verbose_name="Опис")),
                ("publication_date", models.DateField(verbose_name="Дата пубікації")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Статус"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authors.author",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="books.genre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книжка",
                "verbose_name_plural": "Книжки",
                "ordering": ["title"],
            },
        ),
    ]
